### ISSUE TITLE
Polarity in Latvian

### ISSUE THREAD

**Issue by olesar** [UniversalDependencies/UD_Latvian-LVTB#2]
It seems that in the Latvian treebank Polarity=Neg corresponds to Polarity=Pos and v/versa

**Comment by martinpopel** [comment]
Yes, this is easy to fix (I can send a PR).

Another problem is that the negative words (e.g. "Neskaties") have a lemma which contains the negative prefix (e.g. "neskatīties"), although negativeness is clearly inflectional (not lexical) with Latvian verbs. See
https://github.com/UniversalDependencies/docs/issues/372
It seems this is also easy to fix: all the words currently marked with `Polarity=Pos` (which should be `Polarity=Neg`) are actually verbs whose lemma starts with "ne". So I suggest e.g.
```
1  nebūt  būt  VERB <xpos> Polarity=Neg|<other_feats>  ...
```

**Comment by lauma** [comment]
Thanks for noticing! I looked up the transformation code - the polarity feature is completely messed up - not only verbs are switched, but also some particles (but not all) are marked wrong. So I will redo the data transformation and upload version with corrected polarity in the evening.

**Comment by lauma** [comment]
About verb prefix "ne" I am not completely sure. Currently we use lemmas as is from the original corpus, thus, prefix "ne" is not removed.

I could mechanicaly remove prefix from finite verb forms, i.e., lemma of the "neskatos" could be come "skatīties" instead of "neskatīties". However, I can't do the same with participles and converbs, as original treebank contains no polarity marking for those forms. Thus, lemma from "neskatoties", "neskatāms" and "neskatīdamies" will still remain "neskatīties". So, if I chop off the "ne" from finite form lemmas, I loose the information that "neskatos" and "neskatīdamies" are inflectional forms of the same word.

Is it still worth doing it then?

Opinions, please?

**Comment by jnivre** [comment]
I would recommend leaving the lemmas as they are. We obviously need better guidelines for achieving cross-linguistic consistency in lemmas, but before we know for sure what the general guidelines should be in this respect I would advise against doing something rushed at the last minutes (especially since the new version would lose information).

**Comment by martinpopel** [comment]
My opinion is:
* We should distinguish lexical and inflectional features. Lexical feature has the same value for all forms of the same lemma. This depends on the lemmatization and it is language specific (so it should be in the lang-spec documentation). E.g. in Czech (and many other languages I believe), `Polarity` is lexical for pronouns (*nobody, nothing,...*), inflectional for verbs, etc.
* If `Polarity` is inflectional (e.g. with Czech verbs and adjectives), then `Polarity=Neg` should imply the lemma does not have the negative meaning and vice versa. There may be cases where the negative prefix is lexicalized, e.g. there is an adjective *nerudný* in Czech which is historically (several centuries ago) negative, but currently there is no affirmative counterpart *rudný*. So we don't use `Polarity=Neg` with *nerudný* **and** we keep the "ne" prefix in the lemma.
* We should never loose information. I agree with @jnivre that loosing some info in last-minute edits, it is better to claim that Polarity is treated as a lexical feature in UDv2.0 for all parts of speech.

**Comment by lauma** [comment]
Polarity should be fixed in 0317bd7. I hope so.

Regarding to lemmas: for now (version UDv2.0) we will leave lemmas as is, because there is not enough time to implement a good change. For future versions we will have to see, where the general UD consensus on lemmas will take us.

**Comment by lauma** [comment]
Original treebank implemented necessary tagset changes, thus, UDv2.3 will have polarity prefix "ne" removed from negative verbs and participles.
